/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "jni_util.h"
/* Header for class com_intel_xml_rss_util_rexec_UNIXJob */

#ifndef _Included_com_intel_xml_rss_util_rexec_UNIXJob
#define _Included_com_intel_xml_rss_util_rexec_UNIXJob
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_xml_rss_util_rexec_UNIXJob
 * Method:    waitForProcessExit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_intel_xml_rss_util_rexec_UNIXJob_waitForProcessExit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_xml_rss_util_rexec_UNIXJob
 * Method:    forkAndExec
 * Signature: ([B[BI[BI[B[IZ)I
 */
JNIEXPORT jint JNICALL Java_com_intel_xml_rss_util_rexec_UNIXJob_forkAndExec
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jbyteArray, jint, jbyteArray, jintArray, jboolean);

/*
 * Class:     com_intel_xml_rss_util_rexec_UNIXJob
 * Method:    destroyProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_intel_xml_rss_util_rexec_UNIXJob_destroyProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_intel_xml_rss_util_rexec_UNIXJob
 * Method:    stopProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_intel_xml_rss_util_rexec_UNIXJob_stopProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_intel_xml_rss_util_rexec_UNIXJob
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_xml_rss_util_rexec_UNIXJob_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
