/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_xml_rss_util_rexec_UNIXProcessEnvironment */

#ifndef _Included_com_intel_xml_rss_util_rexec_UNIXProcessEnvironment
#define _Included_com_intel_xml_rss_util_rexec_UNIXProcessEnvironment
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_xml_rss_util_rexec_UNIXProcessEnvironment_MIN_NAME_LENGTH
#define com_intel_xml_rss_util_rexec_UNIXProcessEnvironment_MIN_NAME_LENGTH 0L
/*
 * Class:     com_intel_xml_rss_util_rexec_UNIXProcessEnvironment
 * Method:    environ
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_intel_xml_rss_util_rexec_UNIXProcessEnvironment_environ
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
