//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.06 at 12:55:25 PM MSK 
//


package com.intel.bigdata.agent.ganglia.data;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "HOSTS")
public class HOSTS {

    @XmlAttribute(name = "UP", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String up;
    @XmlAttribute(name = "DOWN", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String down;
    @XmlAttribute(name = "SOURCE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String source;

    /**
     * Gets the value of the up property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUP() {
        return up;
    }

    /**
     * Sets the value of the up property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUP(String value) {
        this.up = value;
    }

    /**
     * Gets the value of the down property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOWN() {
        return down;
    }

    /**
     * Sets the value of the down property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOWN(String value) {
        this.down = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOURCE() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOURCE(String value) {
        this.source = value;
    }

}
