//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.06 at 12:55:25 PM MSK 
//


package com.intel.bigdata.agent.ganglia.data;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.intel.bigdata.management.data.ganglia package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.intel.bigdata.management.data.ganglia
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EXTRADATA }
     * 
     */
    public EXTRADATA createEXTRADATA() {
        return new EXTRADATA();
    }

    /**
     * Create an instance of {@link GRID }
     * 
     */
    public GRID createGRID() {
        return new GRID();
    }

    /**
     * Create an instance of {@link CLUSTER }
     * 
     */
    public CLUSTER createCLUSTER() {
        return new CLUSTER();
    }

    /**
     * Create an instance of {@link HOST }
     * 
     */
    public HOST createHOST() {
        return new HOST();
    }

    /**
     * Create an instance of {@link EXTRAELEMENT }
     * 
     */
    public EXTRAELEMENT createEXTRAELEMENT() {
        return new EXTRAELEMENT();
    }

    /**
     * Create an instance of {@link METRICS }
     * 
     */
    public METRICS createMETRICS() {
        return new METRICS();
    }

    /**
     * Create an instance of {@link GANGLIAXML }
     * 
     */
    public GANGLIAXML createGANGLIAXML() {
        return new GANGLIAXML();
    }

    /**
     * Create an instance of {@link HOSTS }
     * 
     */
    public HOSTS createHOSTS() {
        return new HOSTS();
    }

    /**
     * Create an instance of {@link METRIC }
     * 
     */
    public METRIC createMETRIC() {
        return new METRIC();
    }

}
