//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 04:02:13 PM CST 
//


package com.intel.splat.client.model.identityservice.config.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for C14NGenMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="C14NGenMethodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="C14N_exclusive"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "C14NGenMethodType")
@XmlEnum
public enum C14NGenMethodType {

    @XmlEnumValue("C14N_exclusive")
    C_14_N_EXCLUSIVE("C14N_exclusive");
    private final String value;

    C14NGenMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C14NGenMethodType fromValue(String v) {
        for (C14NGenMethodType c: C14NGenMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
