//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 04:02:13 PM CST 
//


package com.intel.splat.client.model.identityservice.config.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignatureGenMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SignatureGenMethodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="rsaWithSha1"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SignatureGenMethodType")
@XmlEnum
public enum SignatureGenMethodType {

    @XmlEnumValue("rsaWithSha1")
    RSA_WITH_SHA_1("rsaWithSha1");
    private final String value;

    SignatureGenMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SignatureGenMethodType fromValue(String v) {
        for (SignatureGenMethodType c: SignatureGenMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
