//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.06 at 12:55:25 PM MSK 
//


package com.intel.bigdata.agent.ganglia.data;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clusterOrGRIDOrHOSTSOrMETRICS"
})
@XmlRootElement(name = "GRID")
public class GRID {

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "AUTHORITY", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authority;
    @XmlAttribute(name = "LOCALTIME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String localtime;
    @XmlElements({
        @XmlElement(name = "CLUSTER", type = CLUSTER.class),
        @XmlElement(name = "GRID", type = GRID.class),
        @XmlElement(name = "HOSTS", type = HOSTS.class),
        @XmlElement(name = "METRICS", type = METRICS.class)
    })
    protected List<Object> clusterOrGRIDOrHOSTSOrMETRICS;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the authority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHORITY() {
        return authority;
    }

    /**
     * Sets the value of the authority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHORITY(String value) {
        this.authority = value;
    }

    /**
     * Gets the value of the localtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCALTIME() {
        return localtime;
    }

    /**
     * Sets the value of the localtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCALTIME(String value) {
        this.localtime = value;
    }

    /**
     * Gets the value of the clusterOrGRIDOrHOSTSOrMETRICS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clusterOrGRIDOrHOSTSOrMETRICS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCLUSTEROrGRIDOrHOSTSOrMETRICS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CLUSTER }
     * {@link GRID }
     * {@link HOSTS }
     * {@link METRICS }
     * 
     * 
     */
    public List<Object> getCLUSTEROrGRIDOrHOSTSOrMETRICS() {
        if (clusterOrGRIDOrHOSTSOrMETRICS == null) {
            clusterOrGRIDOrHOSTSOrMETRICS = new ArrayList<Object>();
        }
        return this.clusterOrGRIDOrHOSTSOrMETRICS;
    }

}
