package com.intel.cedar.agent;

import java.io.OutputStream;

import com.intel.cedar.agent.impl.TaskRunnerStatus;
import com.intel.cedar.agent.runtime.ServerRuntimeInfo;
import com.intel.cedar.tasklet.IResult;
import com.intel.cedar.tasklet.ITaskItem;
import com.intel.cedar.tasklet.ITaskRunner;

public interface IAgent {
    // TODO: return type should be the type generated by JAXB or XStream
    public IResult run(ITaskRunner runner, ITaskItem taskItem,
            String timeout /* seconds */, String cwd);

    public void kill(ITaskRunner runner);

    public TaskRunnerStatus getStatus(ITaskRunner runner);

    public String getRunningId(ITaskRunner runner);

    public void setOutputStream(ITaskRunner runner, OutputStream output);

    public boolean testConnection();

    public ServerRuntimeInfo getServerInfo();

    public String getAgentID();
}
