package com.intel.cedar.service.client.model;

public enum CedarOperation {
    GENERAL, REGISTER_CLOUD, DEREGISTER_CLOUD, ENABLE_CLOUD, DISABLE_CLOUD, EDIT_CLOUD, LAUNCH_INSTANCE, TERMINATE_INSTANCE, QUERY_INSTANCE, LOAD_INSTANCE, ENABLE_PORTMAPPING, ATTACH_VOLUME, CREATE_VOLUME, DELETE_VOLUME, GET_CONSOLEOUTPUT, SHOW_JOB_STATUS, SHOW_HISTORY_INFO, SHOW_LOGIN_INFO,

    DeployFeature, UndeployFeature;
}
