package com.intel.cedar.service.client.model;

import com.extjs.gxt.ui.client.data.BaseModel;

public class InstanceInfoBean extends BaseModel {
    private static final long serialVersionUID = 2036490805702066327L;
    private Long id = -1l;
    private Long cloudId = -1l; // only valid if managed by cloud
    private Long machineId; // refer to the machine's ID
    private String instanceId; // generated by cloud/manager
    private Long typeId; // machine type
    private String state; // Starting/Ready/Shutdown
    private String privateIp; // private IP of the instance
    private String dns; // private DNS of the instance
    private String ip; // actual IP of the instance
    private Long gatewayId = -1l; // refer to gateway
    private Boolean managed; // instance with agent running
    private String comment;
    private String cloudName;
    private String os;
    private String arch;
    private String typeName;
    private UserInfoBean user;
    private Boolean pooled;
    private String remoteDisplay;

    public InstanceInfoBean() {
    }

    public void refresh() {
        set("Cloud", cloudName);
        set("Instance", instanceId);
        set("PrivateIP", privateIp);
        set("PrivateDNS", dns);
        set("IP", ip);
        set("OS", os);
        set("Arch", arch);
        set("Comment", comment);
        set("State", state);
        set("User", user.getUserName());
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCloudId() {
        return cloudId;
    }

    public void setCloudId(Long cloudId) {
        this.cloudId = cloudId;
    }

    public Long getMachineId() {
        return machineId;
    }

    public void setMachineId(Long machineId) {
        this.machineId = machineId;
    }

    public String getInstanceId() {
        return instanceId;
    }

    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }

    public Long getTypeId() {
        return typeId;
    }

    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getPrivateIp() {
        return privateIp;
    }

    public void setPrivateIp(String ip) {
        this.privateIp = ip;
    }

    public String getPrivateDns() {
        return dns;
    }

    public void setPrivateDns(String dns) {
        this.dns = dns;
    }

    public Long getGatewayId() {
        return gatewayId;
    }

    public void setGatewayId(Long gatewayId) {
        this.gatewayId = gatewayId;
    }

    public Boolean getManaged() {
        return managed;
    }

    public void setManaged(Boolean managed) {
        this.managed = managed;
    }

    public String getCloudName() {
        return cloudName;
    }

    public void setCloudName(String cloudName) {
        this.cloudName = cloudName;
    }

    public String getOs() {
        return os;
    }

    public void setOs(String os) {
        this.os = os;
    }

    public String getArch() {
        return arch;
    }

    public void setArch(String arch) {
        this.arch = arch;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public void setPooled(Boolean pooled) {
        this.pooled = pooled;
    }

    public Boolean getPooled() {
        return this.pooled;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Override
    public boolean equals(Object obj) {
        InstanceInfoBean f;
        if (!(obj instanceof InstanceInfoBean))
            return false;
        f = (InstanceInfoBean) obj;
        if (id.equals(f.id) && cloudId.equals(f.cloudId))
            return true;
        return false;
    }

    public UserInfoBean getUser() {
        return user;
    }

    public void setUser(UserInfoBean user) {
        this.user = user;
    }

    public String getRemoteDisplay() {
        return remoteDisplay;
    }

    public void setRemoteDisplay(String remoteDisplay) {
        this.remoteDisplay = remoteDisplay;
    }
}
