#!/bin/bash
#
# chkconfig: - 91 35
# description: Starts and stops the Cloud Test Service
#
##############################################################################
#
#   Copyright 2004 The Apache Software Foundation.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##############################################################################
#
# Small shell script to show how to start/stop Tomcat using jsvc
# If you want to have Tomcat running on port 80 please modify the server.xml
# file:
#
#    <!-- Define a non-SSL HTTP/1.1 Connector on port 80 -->
#    <Connector className="org.apache.catalina.connector.http.HttpConnector"
#               port="80" minProcessors="5" maxProcessors="75"
#               enableLookups="true" redirectPort="8443"
#               acceptCount="10" debug="0" connectionTimeout="60000"/>
#
# That is for Tomcat-5.0.x (Apache Tomcat/5.0)
#
ulimit -n 334535
if [[ @${JAVA_HOME}@ == @@ ]] 
then
  export JRE_HOME=/opt/cedar/jre
else
  export JRE_HOME=${JAVA_HOME}/jre
fi

export JAVA_CMD=${JRE_HOME}/bin/java

if [[ @${CEDAR_HOME}@ == @@ ]] 
then
  export CEDAR_HOME=/opt/cedar
fi

# for multi instances adapt those lines.
TMP_DIR=/var/tmp
PID_FILE=/var/run/cedar_service.pid

CLASSPATH=$CEDAR_HOME/startup/bootstrap.jar:$CEDAR_HOME/startup/commons-daemon.jar
JSVC=${CEDAR_HOME}/startup/jsvc`uname -m`

# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
#else
#  exit 0
fi
case "$1" in
  start)
    rm -f $CEDAR_HOME/log/service.log
    $JSVC \
    -jvm server \
    -home $JRE_HOME \
    -Dcedar.home=$CEDAR_HOME \
    -Djava.cmd=$JAVA_CMD \
    -wait 10 \
    -pidfile $PID_FILE \
    -outfile $CEDAR_HOME/log/service.log \
    -errfile '&1' \
    -cp $CLASSPATH \
    com.intel.cedar.util.CedarApplication \
    service
    #
    # To get a verbose JVM
    #-verbose \
    # To get a debug of jsvc.
    #-debug \
    exit $?
    ;;

  stop)
    $JSVC \
    -stop \
    -pidfile $PID_FILE \
    com.intel.cedar.util.CedarApplication \
    service
    exit $?
    ;;

  *)
    echo "Usage CedarService start/stop"
    exit 1;;
esac
