/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_xml_rss_util_rexec_WindowsProcessEnvironment */

#ifndef _Included_com_intel_xml_rss_util_rexec_WindowsProcessEnvironment
#define _Included_com_intel_xml_rss_util_rexec_WindowsProcessEnvironment
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_DEFAULT_INITIAL_CAPACITY
#define com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_DEFAULT_INITIAL_CAPACITY 16L
#undef com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_MAXIMUM_CAPACITY
#define com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_MAXIMUM_CAPACITY 1073741824L
#undef com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_DEFAULT_LOAD_FACTOR
#define com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_DEFAULT_LOAD_FACTOR 0.75f
#undef com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_serialVersionUID
#define com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_serialVersionUID 362498820763181265i64
#undef com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_MIN_NAME_LENGTH
#define com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_MIN_NAME_LENGTH 1L
/*
 * Class:     com_intel_xml_rss_util_rexec_WindowsProcessEnvironment
 * Method:    environmentBlock
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_environmentBlock
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
