/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_EntryComparator */

#ifndef _Included_com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_EntryComparator
#define _Included_com_intel_xml_rss_util_rexec_WindowsProcessEnvironment_EntryComparator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
